spring:
  application:
    name: banking-account-api

  r2dbc:
    url: r2dbc:h2:mem:///rabodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # parameters required so flyway and r2dbc share same instance

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:rabodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE