CREATE TABLE IF NOT EXISTS accounts (
    ID VARCHAR PRIMARY KEY,
    USER_ID VARCHAR NOT NULL,
    USER_LAST_NAME VARCHAR NOT NULL,
    CARD_ID VARCHAR NOT NULL,
    CARD_TYPE VARCHAR NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL,
    UPDATED_AT DATE NOT NULL
);
